JSON referenced schema support
confluentinc/confluent-kafka-dotnet pull request #2042
Opened 2023-04-25 10:50 UTC by jainruchir

2023-06-05 12:00 UTC, anchitj commented on src/Confluent.SchemaRegistry.Serdes.Json/JsonSerDesSchemaUtils.cs
> +        private void create_schema_dict_util(Schema root)
follow PascalCase for method names

2023-06-09 10:29 UTC, jainruchir commented on examples/JsonWithReferences/Program.cs
> +    // }
I kept it if the user wants to use the convertor function. In that case, this Product class would be used instead of the class with all the members.

2023-06-14 09:38 UTC, anchitj requested changes
Looks good overall. Please add a new entry in changelog as well.

2023-08-25 11:21 UTC, anchitj approved these changes

2023-08-25 11:27 UTC, merged