Feature/admin client scramapi
confluentinc/confluent-kafka-dotnet pull request #2070
Opened 2023-07-03 05:06 UTC by mahajanadhitya

2023-07-03 17:01 UTC, anchitj requested changes
Integration tests are failing. Can we fix that as well please?

2023-07-06 08:10 UTC, anchitj commented
Tried running the tests locally but they seem to be getting stuck indefinitely. Can you please check?

2023-07-06 12:20 UTC, mahajanadhitya commented on src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
> +                throw new KafkaException(errorCode);
Those would all be taken care by the ErrorCode itself.

2023-07-06 12:20 UTC, mahajanadhitya commented on test/Confluent.SchemaRegistry.IntegrationTests/Tests/ProtobufWithReferences.cs
> +            }
Otherwise the tests on Semaphore would fail, as this one is flaky.

2023-07-07 11:40 UTC, anchitj requested changes

2023-07-07 11:40 UTC, anchitj commented on src/Confluent.Kafka/Admin/UserScramCredentialsDescription.cs
> +            return result;
```suggestion
    var errString = Error.IsError ? Error.ToString() : "";
    return $"{User} [ {string.Join(", ",ScramCredentialInfos.Select(info => info.ToString())} ] {errString}";
```

2023-07-07 11:40 UTC, anchitj commented on src/Confluent.Kafka/AdminClient.cs
> +            }
If there is an error why aren't we setting the other fields? Aren't they passed on from Librdkafka?

2023-07-07 11:40 UTC, anchitj commented on src/Confluent.Kafka/AdminClient.cs
> +                }
Can we rewrite it using enumerable to keep the code in the same style like being followed in other methods? Something like
```suggestion
            int count = Librdkafka.DescribeUserScramCredentials_result_get_count(eventPtr);
            List<UserScramCredentialsDescription> descriptions = Enumerable.Range(0, count).Select(i =>
            {
                IntPtr c_Description = Librdkafka.DescribeUserScramCredentials_result_get_description(eventPtr, i);
                IntPtr c_error = Librdkafka.UserScramCredentialsDescription_get_error(c_Description);
                ErrorCode errorCode = Librdkafka.error_code(c_error);
                string errorString = Librdkafka.error_string(c_error);

                var description = new UserScramCredentialsDescription
                {
                    User = PtrToStringUTF8(Librdkafka.UserScramCredentialsDescription_get_user(c_Description)),
                    Error = new Error(errorCode, errorString)
                };

                if (errorCode == 0)
                {
                    int numCredentials = Librdkafka.UserScramCredentialsDescription_get_scramcredentialinfo_cnt(c_Description);
                    description.ScramCredentialInfos = Enumerable.Range(0, numCredentials).Select(j =>
                    {
                        IntPtr c_ScramCredentialInfo = Librdkafka.UserScramCredentialsDescription_get_scramcredentialinfo(c_Description, j);
                        return new ScramCredentialInfo
                        {
                            Mechanism = (ScramMechanism)Librdkafka.ScramCredentialInfo_get_mechanism(c_ScramCredentialInfo),
                            Iterations = Librdkafka.ScramCredentialInfo_get_iterations(c_ScramCredentialInfo)
                        };
                    }).ToList();
                }

                return description;
            }).ToList();

            return new DescribeUserScramCredentialsResult
            {
                Error = new Error(ErrorCode.NoError),
                UserScramCredentialsDescriptions = descriptions
            };

```

2023-07-07 11:40 UTC, anchitj commented on src/Confluent.Kafka/AdminClient.cs
> +            }
Same, try if we can use Enumerable

2023-07-07 11:40 UTC, anchitj commented on src/Confluent.Kafka/Admin/AlterUserScramCredentialsResult.cs
> +        public List<AlterUserScramCredentialsReport> AlterUserScramCredentialsReports { get; set;}
Don't use `AlterUserScramCredentialsReports` in `AlterUserScramCredentialsResult`. Rather add all the fields again here, except Error

2023-07-07 11:40 UTC, anchitj commented on src/Confluent.Kafka/Admin/DescribeUserScramCredentialsResult.cs
> +//
Why we don't have the `DescribeUserScramCredentialsReport`?

2023-07-07 11:40 UTC, anchitj commented on src/Confluent.Kafka/AdminClient.cs
> +                                        break;
You aren't throwing `DescribeUserCredentialsException` anywhere?
```suggestion
case Librdkafka.EventType.DescribeUserScramCredentials_Result:
{
    if (errorCode != ErrorCode.NoError)
    {
        Task.Run(() =>
                ((TaskCompletionSource<DescribeUserScramCredentialsResult>)adminClientResult).TrySetException(
                    new KafkaException(kafkaHandle.CreatePossiblyFatalError(errorCode, errorStr))));
            break;
    }
    var results = extractDescribeUserScramCredentialsResult(eventPtr);
    if (results.Error != null && results.Error.IsError)
    {
        Task.Run(() =>
                ((TaskCompletionSource<DescribeUserScramCredentialsResult>)adminClientResult).TrySetException(
                    new DescribeUserScramCredentialsException(results)));
    }
    else
    {
        Task.Run(() =>
            ((TaskCompletionSource<DescribeUserScramCredentialsResult>)adminClientResult).TrySetResult(
                new DescribeUserScramCredentialsResult() { UserScramCredentialsDescriptions = results.UserScramCredentialsDescriptions }
        ));
    }
    break;
}
```

2023-07-07 11:40 UTC, anchitj commented on src/Confluent.Kafka/AdminClient.cs
> +                                    }
Same as above

2023-07-07 11:40 UTC, anchitj commented on src/Confluent.Kafka/AdminClient.cs
> +        /// </returns>
Only need to keep the summary

2023-07-07 11:40 UTC, anchitj commented on src/Confluent.Kafka/AdminClient.cs
> +        /// </returns>
Only need to keep the summary

2023-07-07 11:54 UTC, anchitj requested changes

2023-07-07 11:54 UTC, anchitj commented on src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
> +                optionsPtr, resultQueuePtr);
Indentation

2023-07-07 11:54 UTC, anchitj commented on src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
> +                }
Don't throw this.

2023-07-07 11:54 UTC, anchitj commented on src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
> +                }
Don't throw this.

2023-07-07 11:54 UTC, anchitj commented on src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
> +                        throw new ArgumentException("Every Alteration must be either an instance of Deletion or Upsertion Subclass");
`Every alteration must be either a Deletion or Upsertion`.

2023-07-07 12:00 UTC, anchitj commented on test/Confluent.Kafka.IntegrationTests/Tests/AdminClient_UserScram.cs
> +                    Assert.Equal(ErrorCode.NoError,alterReport.Error.Code);
Can we add assert for User here?

2023-07-07 12:04 UTC, anchitj commented
Also add a CHANGELOG entry

2023-07-10 06:21 UTC, anchitj reviewed
Verified all the integration tests are passing against `feature/userscram-AdminClient` librdkafka.

2023-07-10 13:06 UTC, anchitj approved these changes
LGTM. Just need to add changelog before merging.

2023-07-10 17:46 UTC, anchitj approved these changes
Thanks for the tests. LGTM. Probably needs a rebase with the master as it's showing conflict in the CHANGELOG.

2023-07-12 06:04 UTC, merged