Methods for working with compatibility
confluentinc/confluent-kafka-dotnet pull request #2097
Opened 2023-08-07 18:55 UTC by ISBronny

Hi!

I've added the missing compatibility types and methods to work with them.

2023-08-09 15:56 UTC, ISBronny commented
@anchitj looks like you're in charge of the review. Have a look, please.

2023-08-26 18:07 UTC, ISBronny commented
@anchitj please review MR. These methods are in the Java implementation and must be here.

2023-08-31 11:20 UTC, anchitj requested changes
Thanks for the changes. Can you please also add a test in `test/Confluent.SchemaRegistry.IntegrationTests` testing the new APIs?

2023-08-31 11:20 UTC, anchitj commented on src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
> +            => await restService.GetGlobalCompatibilityAsync();
They can be merged, to align with the Java API https://github.com/confluentinc/schema-registry/blob/2d1127f05799d1e60f6702e246cca80a7061e50a/client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java#L237-L239

2023-08-31 11:20 UTC, anchitj commented on src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
> +            => await restService.SetGlobalCompatibilityAsync(compatibility);
Same as above for merging, and renamed to `UpdateComatibilityAsync`. 

Also, I think we should return Compatibility to keep it aligned with the Java API https://github.com/confluentinc/schema-registry/blob/2d1127f05799d1e60f6702e246cca80a7061e50a/client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java#L232-L235

2023-08-31 11:20 UTC, anchitj commented on src/Confluent.SchemaRegistry/ISchemaRegistryClient.cs
> +        /// <returns></returns>
Update return tags here and below

2023-08-31 11:20 UTC, anchitj commented on src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
> +            => await restService.GetGlobalCompatibilityAsync();
Also add ConfigureAwait here and below

2023-08-31 22:08 UTC, ISBronny commented
Thanks for the feedback. I fixed everything

2023-09-01 07:13 UTC, anchitj requested changes
Looks good. One minor change needed, then we can merge. Also created a PR to run our CI against these changes https://github.com/confluentinc/confluent-kafka-dotnet/pull/2111

2023-09-01 07:13 UTC, anchitj commented on src/Confluent.SchemaRegistry/Rest/RestService.cs
>                          .ConfigureAwait(continueOnCapturedContext: false)).CompatibilityLevel;
This can be removed

2023-09-01 08:29 UTC, ISBronny commented
Fixed

2023-09-01 09:14 UTC, anchitj approved these changes
Thanks for the changes.

2023-09-01 09:14 UTC, merged