#2183 switch to licence expression + repo info
confluentinc/confluent-kafka-dotnet pull request #2192
Opened 2024-02-22 09:53 UTC by thompson-tomo

This sets additional package info and switch to licence expression rather than url. Also lint csproj to be consistantly tabbed.

closes #2183

2024-04-08 09:37 UTC, anchitj requested changes
Thanks for the contribution. Left some minor nitpicks.

2024-04-08 09:37 UTC, anchitj commented on src/Confluent.Kafka/Confluent.Kafka.csproj
> +	<RepositoryUrl>https://github.com/confluentinc/confluent-kafka-dotnet/</RepositoryUrl>
Can we update it to `https://github.com/confluentinc/confluent-kafka-dotnet.git` everywhere

2024-04-08 09:37 UTC, anchitj commented on src/Confluent.Kafka/Confluent.Kafka.csproj
> +	<RepositoryType>Git</RepositoryType>
Let's use lowercase `git` everywhere

2024-04-08 09:37 UTC, anchitj commented on src/Confluent.Kafka/Confluent.Kafka.csproj
> +	<PackageIconUrl>https://raw.githubusercontent.com/confluentinc/confluent-kafka-dotnet/master/confluent-logo.png</PackageIconUrl>
Can we please also add `PackageIcon` while keeping this `PackageIconUrl` as well as it seems `PackageIconUrl` is deprecated.

2024-04-08 09:37 UTC, anchitj commented on src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj
> +	<RepositoryType>Git</RepositoryType><PackageIconUrl>https://raw.githubusercontent.com/confluentinc/confluent-kafka-dotnet/master/confluent-logo.png</PackageIconUrl>
Line break

2024-04-08 09:44 UTC, thompson-tomo commented
Will make the changes tomorrow/tonight.

2024-04-09 07:00 UTC, anchitj approved these changes
Thanks for the changes. I've pushed a commit to fix some typos and tabs with spaces.

2024-07-10 07:12 UTC, emasab approved these changes

2024-07-10 09:44 UTC, anchitj commented
Tested in https://github.com/confluentinc/confluent-kafka-dotnet/pull/2250

2024-07-10 09:54 UTC, emasab approved these changes

2024-07-10 09:54 UTC, merged

2024-07-26 15:24 UTC, rogerbriggen-securiton commented on src/Confluent.Kafka/Confluent.Kafka.csproj
> +    <PackageLicenceExpression>Apache-2.0</PackageLicenceExpression>
must be PackageLicenseExpression, see https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg#project-properties