Add Kafka Core to Third-Party Libraries
confluentinc/confluent-kafka-dotnet pull request #2361
Opened 2024-11-20 17:44 UTC by ffernandolima

This PR introduces the Kafka Core library to the list of third-party libraries.

Kafka Core empowers developers to effortlessly build robust .NET applications on top of Confluent Kafka, focusing on simplicity, maintainability, and extensibility. With intuitive abstractions and builders, it introduces powerful features that enhance functionality and extend the official library's capabilities.

2024-11-21 07:57 UTC, anchitj requested changes

2024-11-21 07:57 UTC, anchitj commented on 3RD_PARTY.md
> +- [Kafka Core](https://github.com/ffernandolima/confluent-kafka-core-dotnet) - Kafka Core empowers developers to build robust .NET applications on top of Confluent Kafka, focusing on simplicity, main
We're maintaining this list in the order libraries were added. Can you please add it to the last?

2024-11-26 16:32 UTC, ffernandolima commented
Hi @anchitj! Could you please review it again?

2024-11-29 06:57 UTC, anchitj approved these changes

2024-11-29 06:58 UTC, merged